'use strict';

/**
 * @ngdoc function
 * @name clientTestApp.controller:BookingcalendarCtrl
 * @description
 * # BookingcalendarCtrl
 * Controller of the clientTestApp
 */
angular.module('clientTestApp')
  .controller('BookingcalendarCtrl', function ($scope, $http, AuthService, Booking, Informer) {
  
  $scope.allInfos = Informer.allInfos;  
  $scope.removeInfos = Informer.remove;

    $scope.agendaDay = 'Day';
    $scope.agendaWeek = 'Week';
    $scope.agendaMonth = 'Month';
    
	$scope.$watch(AuthService.isLoggedIn, function(isLoggedIn) {
		$scope.isLoggedIn = isLoggedIn;
		$scope.user = AuthService.currentUser();
	});

        $scope.events = [];

    $scope.eventsF = function (start, end, callback) {
        $scope.events.length = 0;
        $http
            .get(
            'http://localhost:8080/book-my-wings/rest/bookings?start=0&pageSize=1000')
            .success(function(data) {
                angular.forEach(data, function (aBooking, key) {
                    var singleEvent = {
                            id : aBooking.bookingId,
                            title : aBooking.aircraft.registration + ' ' + aBooking.pilot.firstName,
                            start : new Date(aBooking.start),
                            end : new Date(aBooking.end),
                            allDay : false
                    }
                    $scope.events.push(singleEvent);
                });
            }).error(function(data, status) {
                
            });
        callback($scope.events);
    };

    /* alert on eventClick */
    $scope.alertOnEventClick = function( event, allDay, jsEvent, view ){
        $scope.startTime = event.start;
        $scope.endTime = event.end;
    };
    /* alert on Drop */
     $scope.alertOnDrop = function(event, dayDelta, minuteDelta, allDay, revertFunc, jsEvent, ui, view){
       $scope.alertMessage = ('Event Droped to make dayDelta ' + dayDelta);
    };
    /* alert on Resize */
    $scope.alertOnResize = function(event, dayDelta, minuteDelta, revertFunc, jsEvent, ui, view ){
       $scope.alertMessage = ('Event Resized to make dayDelta ' + minuteDelta);
    };
    /* handle the events generated by clicking the day(empty spot) in the calendar */
    $scope.dayClick = function( date, allDay, jsEvent, view ){
          $scope.currentDate = date;
          $scope.alertMessage = ('Please choose booking-time for ' + $.datepicker.formatDate('dd.mm.yy', date));
    };

    /* add and removes an event source of choice */
    $scope.addRemoveEventSource = function(sources,source) {
      var canAdd = 0;
      angular.forEach(sources,function(value, key){
        if(sources[key] === source){
          sources.splice(key,1);
          canAdd = 1;
        }
      });
      if(canAdd === 0){
        sources.push(source);
      }
    };
    /* add custom event*/
    $scope.addEvent = function() {
    	
    	var startDate = new Date();
    	startDate.setTime($scope.currentDate.getTime()); //to set dd/mm//yy
    	startDate.setHours($scope.startTime.getHours(), $scope.startTime.getMinutes(), 0, 0);

    	var endDate = new Date();
    	endDate.setTime($scope.currentDate.getTime()); //to set dd/mm//yy
    	endDate.setHours($scope.endTime.getHours(), $scope.endTime.getMinutes(), 0, 0);
    	
    	var booking = {
    			aircraft : $scope.aircraft,
    			pilot : AuthService.currentUser(),    			
    			start : startDate,
    			end : endDate
    	};

        Booking.addBooking(booking);
      
    };
    /* remove event */
    $scope.remove = function(index) {
      $scope.events.splice(index,1);
    };
    /* Change View */
    $scope.changeView = function(view,calendar) {
      calendar.fullCalendar('changeView',view);
    };
    /* Change View */
    $scope.renderCalender = function(calendar) {
      if(calendar){
        calendar.fullCalendar('render');
      }
    };
    /* config object */
    $scope.uiConfig = {
      calendar:{
        height: 450,
        editable: true,
        header:{
          left: 'title',
          center: '',
          right: 'today prev,next'
        },
        eventClick: $scope.alertOnEventClick,
        eventDrop: $scope.alertOnDrop,
        eventResize: $scope.alertOnResize,
        dayClick: $scope.dayClick,
        defaultView: 'agendaWeek'
      }
    };
    $scope.uiConfig.calendar.dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    $scope.uiConfig.calendar.dayNamesShort = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    $scope.agendaDay = 'Day';
    $scope.agendaWeek = 'Week';
    $scope.agendaMonth = 'Month';

    /* event sources array*/
    $scope.eventSources = [$scope.events, $scope.eventSource, $scope.eventsF];

    // Timepicker-Config
    $scope.startTime = new Date();
    $scope.startTime.setHours('8', '00', '0', '0');
    $scope.endTime = new Date();
    $scope.endTime.setHours('18', '00', '0', '0');
  
    $scope.hstep = 1;
    $scope.mstep = 30;
    $scope.ismeridian = false;
    
	$scope.title = 'Please choose aircraft';

	$scope.status = {
		isopen : false
	};

	$scope.toggled = function(aircraft) {
		$scope.title = aircraft.registration;
		$scope.aircraft = aircraft;
		$scope.status.isopen = !$scope.status.isopen;
	};

	$http
			.get(
					'http://localhost:8080/book-my-wings/rest/aircrafts/business/pilot/' + AuthService.currentUser().id)
			.success(function(data) {
				$scope.aircrafts = data;
			}).error(function(data, status) {

			});	

  });