'use strict';

/**
 * @ngdoc function
 * @name clientTestApp.controller:BookingcalendarCtrl
 * @description
 * # BookingcalendarCtrl
 * Controller of the clientTestApp
 */
angular.module('clientTestApp')
  .controller('BookingcalendarCtrl', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];

    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();
    
    $scope.changeTo = 'German';
    $scope.agendaDay = 'Day';
    $scope.agendaWeek = 'Week';
    $scope.agendaMonth = 'Month';
    /* event source that contains custom events on the scope */
    $scope.events = [
      {title: 'All Day Event',start: new Date(y, m, 1)},
      {title: 'Long Event',start: new Date(y, m, d - 5),end: new Date(y, m, d - 2)},
      {id: 999,title: 'Repeating Event',start: new Date(y, m, d - 3, 16, 0),allDay: false},
      {id: 999,title: 'Repeating Event',start: new Date(y, m, d + 4, 16, 0),allDay: false},
      {title: 'Birthday Party',start: new Date(y, m, d + 1, 19, 0),end: new Date(y, m, d + 1, 22, 30),allDay: false},
      {title: 'Click for Google',start: new Date(y, m, 28),end: new Date(y, m, 29),url: 'http://google.com/'}
    ];
    /* event source that calls a function on every view switch */
    $scope.eventsF = function (start, end, callback) {
      callback($scope.events);
    };

    /* alert on eventClick */
    $scope.alertOnEventClick = function( event, allDay, jsEvent, view ){
        $scope.alertMessage = (event.title + ' was clicked ');
    };
    /* alert on Drop */
     $scope.alertOnDrop = function(event, dayDelta, minuteDelta, allDay, revertFunc, jsEvent, ui, view){
       $scope.alertMessage = ('Event Droped to make dayDelta ' + dayDelta);
    };
    /* alert on Resize */
    $scope.alertOnResize = function(event, dayDelta, minuteDelta, revertFunc, jsEvent, ui, view ){
       $scope.alertMessage = ('Event Resized to make dayDelta ' + minuteDelta);
    };
    /* handle the events generated by clicking the day(empty spot) in the calendar */
    $scope.dayClick = function( date, allDay, jsEvent, view ){
          $scope.currentDate = date;
          $scope.alertMessage = ('Please choose booking-time for ' + $.datepicker.formatDate('dd.mm.yy', date));
    };

    /* add and removes an event source of choice */
    $scope.addRemoveEventSource = function(sources,source) {
      var canAdd = 0;
      angular.forEach(sources,function(value, key){
        if(sources[key] === source){
          sources.splice(key,1);
          canAdd = 1;
        }
      });
      if(canAdd === 0){
        sources.push(source);
      }
    };
    /* add custom event*/
    $scope.addEvent = function() {
      alert('About to add booking: ' +   'start: ' +  $scope.currentDate + 'startTIme ' + $scope.startTime);
    };
    /* remove event */
    $scope.remove = function(index) {
      $scope.events.splice(index,1);
    };
    /* Change View */
    $scope.changeView = function(view,calendar) {
      calendar.fullCalendar('changeView',view);
    };
    /* Change View */
    $scope.renderCalender = function(calendar) {
      if(calendar){
        calendar.fullCalendar('render');
      }
    };
    /* config object */
    $scope.uiConfig = {
      calendar:{
        height: 450,
        editable: true,
        header:{
          left: 'title',
          center: '',
          right: 'today prev,next'
        },
        eventClick: $scope.alertOnEventClick,
        eventDrop: $scope.alertOnDrop,
        eventResize: $scope.alertOnResize,
        dayClick: $scope.dayClick,
        defaultView: 'agendaWeek'
      }
    };
    $scope.uiConfig.calendar.dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    $scope.uiConfig.calendar.dayNamesShort = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    $scope.changeTo = 'German';
    $scope.agendaDay = 'Day';
    $scope.agendaWeek = 'Week';
    $scope.agendaMonth = 'Month';

    /* event sources array*/
    $scope.eventSources = [$scope.events, $scope.eventSource, $scope.eventsF]; 

  })
  
  .controller( 'TimpickerController', function ($scope) {
	  $scope.startTime = new Date();
	  $scope.startTime.setHours('8', '00', '0', '0');
	  $scope.endTime = new Date();
	  $scope.endTime.setHours('18', '00', '0', '0');
	
	  $scope.hstep = 1;
	  $scope.mstep = 30;
	  $scope.ismeridian = false;
	
	
	  $scope.clear = function() {
	    $scope.startTime = null;
	  };
  });